
package ventanas;


import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.math.BigInteger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import misclases.Cliente;
import system.DataBase;

/**
 *
 * @author Asus
 */
public class ClientManagement extends javax.swing.JFrame {
   DataBase db = new DataBase();
   Connection conexion = db.getConnected();
   DefaultTableModel modelo;
   private int ZipCode;
   private BigInteger Phone;
   private BigInteger PhoneHome;
   int xMouse, yMouse;
   Cliente client = null;

    public ClientManagement() {
        initComponents();
        setLocationRelativeTo(null);
        query();
     
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        inputLNP = new javax.swing.JTextField();
        inputLNM = new javax.swing.JTextField();
        inputAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputCol = new javax.swing.JTextField();
        inputZC = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputPhone = new javax.swing.JTextField();
        inputPhoneHome = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addData = new javax.swing.JButton();
        editData = new javax.swing.JButton();
        deletData = new javax.swing.JButton();
        showData = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        goServices = new javax.swing.JButton();
        goEmployees = new javax.swing.JButton();
        goClients = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("ID:");

        inputID.setEditable(false);

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        inputLNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLNPActionPerformed(evt);
            }
        });

        inputLNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLNMActionPerformed(evt);
            }
        });

        jLabel7.setText("Colonia:");

        jLabel8.setText("Email:");

        jLabel9.setText("Codigo Postal:");

        jLabel10.setText("Telefono Cel:");

        jLabel11.setText("Telefono Casa:");

        inputCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputColActionPerformed(evt);
            }
        });

        registerButton.setText("Registrar");
        registerButton.setEnabled(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(51, 51, 51)
                                    .addComponent(inputName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputLNP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(45, 45, 45)
                                    .addComponent(inputAddress))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputLNM, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputZC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(inputCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(inputZC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(inputPhoneHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        addData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        addData.setText("Agregar");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        editData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        editData.setText("Modificar");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });

        deletData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        deletData.setText("Eliminar");
        deletData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletDataActionPerformed(evt);
            }
        });

        showData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        showData.setText("Mostrar Datos");
        showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(showData, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 724, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ClienteId", "Nombre", "Apellido Paterno", "Apellido Materno", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        Tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 724, 212));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 30));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        goServices.setText("Servicios");
        goServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goServicesActionPerformed(evt);
            }
        });

        goEmployees.setText("Empleados");
        goEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goEmployeesActionPerformed(evt);
            }
        });

        goClients.setText("Clientes");
        goClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goClientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(goClients, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(goServices, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addComponent(goEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(goClients, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goServices, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(goEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(617, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 780));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("Administracion de clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 37));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputLNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLNPActionPerformed

    private void inputLNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLNMActionPerformed

    private void inputColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputColActionPerformed

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        // TODO add your handling code here:
        
        registerButton.setEnabled(false);
        modify();
        query();
    }//GEN-LAST:event_editDataActionPerformed

    private void showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataActionPerformed
        // TODO add your handling code here:
        registerButton.setEnabled(false);
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un cliente.");
        } else {
       
        String consulta = "select * from cliente where clienteId=?";
    
        try {
    PreparedStatement ps = conexion.prepareStatement(consulta);
    ps.setInt(1, Integer.parseInt(inputID.getText()));
    ResultSet res = ps.executeQuery();
    
        if (res.next()) {
            client = new Cliente(
                res.getString("email"),
                res.getString("tel_cel"),
                res.getString("direccion"), 
                res.getString("colonia"), 
                Integer.parseInt(res.getString("zp")), 
                res.getString("nombre"), 
                res.getString("apellidoP"), 
                res.getString("apellidoM"), 
                res.getInt("clienteId"), 
                res.getString("tel_casa"));
            
            JOptionPane.showMessageDialog(this,client.showData());
                 }

        } catch(SQLException err) {
            System.out.println("Hubo un error para consultar los datos en modify de cliente: " + err);
        }
       }
    }//GEN-LAST:event_showDataActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        clearInputs();
        registerButton.setEnabled(true);
        inputID.setEditable(false);

    }//GEN-LAST:event_addDataActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        addData();
        query();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void deletDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletDataActionPerformed
        // TODO add your handling code here:
        registerButton.setEnabled(false);
        deleteData();
        query();
    }//GEN-LAST:event_deletDataActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        registerButton.setEnabled(false);
        int fila = Tabla.getSelectedRow();
  
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "No se encontro la fila.");
        } else {
            
            int clienteId = Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0)));
//            Tabla.setCellSelectionEnabled(true);
//            String nom = (String) Tabla.getValueAt(fila, 1);
//            String ape = (String) Tabla.getValueAt(fila, 2);
//            String puestoE = (String) Tabla.getValueAt(fila, 3);
            
            String sql = "select * from cliente where clienteId=?";
            try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setInt(1, clienteId);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()){
                 inputID.setText(""+clienteId);
                 inputName.setText(rs.getString("nombre"));
                 inputLNP.setText(rs.getString("apellidoP"));
                 inputLNM.setText(rs.getString("apellidoM"));
                 inputAddress.setText(rs.getString("direccion"));
                 inputCol.setText(rs.getString("colonia"));
                 inputZC.setText(rs.getString("zp"));
                 inputEmail.setText(rs.getString("email"));
                 inputPhoneHome.setText(rs.getString("tel_casa"));
                 inputPhone.setText(rs.getString("tel_cel"));
            }
           
        }catch (SQLException e){
            System.out.println("Hubo un error para consultar los datos en tablamouseclicked: " + e);
        }
           
            
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void TablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaPropertyChange
        // TODO add your handling code here:
    
    }//GEN-LAST:event_TablaPropertyChange

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y- yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void goServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goServicesActionPerformed
        // TODO add your handling code here:
        ServicesManagement sm = new ServicesManagement();
        sm.setVisible(true);
        sm.pack();
        this.dispose();
    }//GEN-LAST:event_goServicesActionPerformed

    private void goEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement();
        em.setVisible(true);
        em.pack();
        this.dispose();
    }//GEN-LAST:event_goEmployeesActionPerformed

    private void goClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goClientsActionPerformed

    private void addData(){
        Map<String, String> lista = new LinkedHashMap<>();
        String errorMessage = "";
        
        lista.put("Nombre", inputName.getText());
        lista.put("Apellido Paterno", inputLNP.getText());
        lista.put("Apellido Materno", inputLNM.getText());
        lista.put("Direccion", inputAddress.getText());
        lista.put("Colonia", inputCol.getText());
        lista.put("Codigo Postal", inputZC.getText());
        lista.put("Correo", inputEmail.getText());
        lista.put("Telefono Cel", inputPhone.getText());
        lista.put("Telefono Casa", inputPhoneHome.getText());
        
        
        for (Map.Entry<String, String> entry : lista.entrySet()) {
            if (entry.getValue().isEmpty()) {
                errorMessage += entry.getKey() + ", ";
            }
        }
        
                 int lastIndex = errorMessage.lastIndexOf(",");
        if (lastIndex >= 0) {
            errorMessage = errorMessage.substring(0, lastIndex) + "." + errorMessage.substring(lastIndex + 1);
        }
        if (!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(this, "Los siguientes campos deben ser completados: " + errorMessage);
        } else {
             try {
                ZipCode = Integer.parseInt(inputZC.getText());
                try {
                    Phone = new BigInteger(inputPhone.getText());
                    
                    try {
                        PhoneHome = new BigInteger(inputPhoneHome.getText());
                        if(inputEmail.getText().contains("@") && inputEmail.getText().contains(".") && !inputEmail.getText().contains(" ")){
            
                         db.insertClientData(lista);
                         
                     } else {
                             JOptionPane.showMessageDialog(this, "El correo ingresado no es valido\nIntentalo de nuevo.");
                        }
                    }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "El telefono de casa debe ser numerico.");
                    }
 
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "El telefono de celular debe ser numerico.");
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El codigo postal debe ser numerico.");
            }
//                db.insertEmployeeData(lista);
        }
        
        clearTable();
        clearInputs();
    }
    
    private void query(){
        String sql = "select * from cliente";
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Object[] cliente = new Object[5];
            modelo = (DefaultTableModel) Tabla.getModel();
            
            while(rs.next()){
                cliente [0] = rs.getInt("clienteId");
                cliente [1] = rs.getString("nombre");
                cliente [2] = rs.getString("apellidoP");
                cliente [3] = rs.getString("apellidoM");
                cliente [4] = rs.getString("tel_cel");
                
                modelo.addRow(cliente);
                
            }
            Tabla.setModel(modelo);
        }catch (SQLException e){
            System.out.println("Hubo un error para consultar los datos: " + e);
        }
    }
    
    private void modify(){
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un cliente.");
        } else {
        Map<String, String> lista = new LinkedHashMap<>();
        String errorMessage = "";
        
        lista.put("Nombre", inputName.getText());
        lista.put("Apellido Paterno", inputLNP.getText());
        lista.put("Apellido Materno", inputLNM.getText());
        lista.put("Direccion", inputAddress.getText());
        lista.put("Colonia", inputCol.getText());
        lista.put("Codigo Postal", inputZC.getText());
        lista.put("Correo", inputEmail.getText());
        lista.put("Telefono Cel", inputPhone.getText());
        lista.put("Telefono Casa", inputPhoneHome.getText());
        
        for (Map.Entry<String, String> entry : lista.entrySet()) {
            if (entry.getValue().isEmpty()) {
                errorMessage += entry.getKey() + ", ";
            }
        }
        
                 int lastIndex = errorMessage.lastIndexOf(",");
        if (lastIndex >= 0) {
            errorMessage = errorMessage.substring(0, lastIndex) + "." + errorMessage.substring(lastIndex + 1);
        }
        if (!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(this, "Los siguientes campos no pueden estar vacios: " + errorMessage);
        } else {
             try {
                ZipCode = Integer.parseInt(inputZC.getText());
                try {
                    Phone = new BigInteger(inputPhone.getText());
                    try {
                        PhoneHome = new BigInteger(inputPhoneHome.getText());
                        if(inputEmail.getText().contains("@") && inputEmail.getText().contains(".") && !inputEmail.getText().contains(" ")){
            
                         db.editClientData(lista, Integer.parseInt(inputID.getText()));
                         
                     } else {
                             JOptionPane.showMessageDialog(this, "El correo ingresado no es valido\nIntentalo de nuevo.");
                        }
                    }catch(NumberFormatException e){
                        JOptionPane.showMessageDialog(this, "El telefono de casa debe ser numerico.");
                    }
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "El numero de telefono debe ser numerico.");
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El codigo postal debe ser numerico.");
            }
//                db.insertEmployeeData(lista);
        }
       }
        
        clearTable();
        clearInputs();
    }
    
    private void deleteData(){
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un cliente.");
        } else {
       String sql = "delete from cliente where clienteId=?";
       int r = 0;
       try{
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(inputID.getText()));
                r = ps.executeUpdate();
                 
                if(r != 0 ){
                    JOptionPane.showMessageDialog(this, "¡Se eliminaron los datos correctamente!");
                }
                    
            } catch (SQLException err) {
                
                System.out.println("Hubo un error al eliminar datos en la tabla cliente: " + err);
                
            }
        }
      
        clearTable();
        clearInputs();
    }
    
    private void clearTable(){
        while (Tabla.getRowCount() > 0){
        modelo.removeRow(0);
        }
    }
    
    
    public void clearInputs(){
        inputID.setText("");
        inputName.setText("");
        inputLNP.setText("");
        inputLNM.setText("");
        inputAddress.setText("");
        inputCol.setText("");
        inputZC.setText("");
        inputEmail.setText("");
        inputPhoneHome.setText("");
        inputPhone.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientManagement().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton addData;
    private javax.swing.JButton deletData;
    private javax.swing.JButton editData;
    private javax.swing.JButton goClients;
    private javax.swing.JButton goEmployees;
    private javax.swing.JButton goServices;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputCol;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputLNM;
    private javax.swing.JTextField inputLNP;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputPhoneHome;
    private javax.swing.JTextField inputZC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showData;
    // End of variables declaration//GEN-END:variables
}
