
package ventanas;

import java.sql.Connection;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import java.math.BigInteger;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import misclases.Empleado;
import system.DataBase;

/**
 *
 * @author Asus
 */
public class EmployeeManagement extends javax.swing.JFrame {
   DataBase db = new DataBase();
   Connection conexion = db.getConnected();
   DefaultTableModel modelo;
   private int ZipCode;
   private BigInteger Phone;
 
   int xMouse, yMouse;
   Empleado employee = null;

    public EmployeeManagement() {
        initComponents();
        setLocationRelativeTo(null);
        query();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputID = new javax.swing.JTextField();
        inputName = new javax.swing.JTextField();
        inputLNP = new javax.swing.JTextField();
        inputLNM = new javax.swing.JTextField();
        inputAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        inputCol = new javax.swing.JTextField();
        inputZC = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        inputPhone = new javax.swing.JTextField();
        inputPuesto = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        addData = new javax.swing.JButton();
        editData = new javax.swing.JButton();
        deletData = new javax.swing.JButton();
        showData = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JButton();
        btnPets = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnDiscounts = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("Administracion de empleados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 41, -1, 37));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido Paterno:");

        jLabel4.setText("Apellido Materno:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("ID:");

        inputID.setEditable(false);

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        inputLNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLNPActionPerformed(evt);
            }
        });

        inputLNM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLNMActionPerformed(evt);
            }
        });

        jLabel7.setText("Colonia:");

        jLabel8.setText("Email:");

        jLabel9.setText("Codigo Postal:");

        jLabel10.setText("Telefono:");

        jLabel11.setText("Puesto / Cargo:");

        inputCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputColActionPerformed(evt);
            }
        });

        registerButton.setText("Registrar");
        registerButton.setEnabled(false);
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerButton)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(51, 51, 51)
                                    .addComponent(inputName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputLNP, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(45, 45, 45)
                                    .addComponent(inputAddress))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(inputLNM, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(inputPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputZC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCol, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(inputCol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(inputZC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLNP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputLNM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(inputPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(inputPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 84, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Operaciones"));

        addData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        addData.setText("Agregar");
        addData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDataActionPerformed(evt);
            }
        });

        editData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        editData.setText("Modificar");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });

        deletData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        deletData.setText("Eliminar");
        deletData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletDataActionPerformed(evt);
            }
        });

        showData.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        showData.setText("Mostrar Datos");
        showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(showData, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deletData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showData, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 408, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Empleados"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpleadoId", "Nombre", "Apellido", "Puesto / Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        Tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(266, 266, 266))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 577, -1, 212));

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        btnEmployee.setText("Empleados");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnPets.setText("Mascotas");
        btnPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetsActionPerformed(evt);
            }
        });

        btnClient.setText("Clientes");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });

        btnDiscounts.setText("Descuentos");
        btnDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountsActionPerformed(evt);
            }
        });

        btnServices.setText("Servicios");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnLogs.setText("Registros");
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });

        btnMain.setText("Menu Prinpal");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiscounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnClient, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPets, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputLNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLNPActionPerformed

    private void inputLNMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLNMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLNMActionPerformed

    private void inputColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputColActionPerformed

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        // TODO add your handling code here:
        
        registerButton.setEnabled(false);
        modify();
        query();
    }//GEN-LAST:event_editDataActionPerformed

    private void showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showDataActionPerformed
        // TODO add your handling code here:
        registerButton.setEnabled(false);
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un empleado.");
        } else {
        String consulta = "select * from empleado_user where empleadoId=?";
        try {
    PreparedStatement ps = conexion.prepareStatement(consulta);
    ps.setInt(1, Integer.parseInt(inputID.getText()));
    ResultSet res = ps.executeQuery();
    if (res.next()){
        String query = "select * from empleado where empleadoId=?";
        PreparedStatement ps_e = conexion.prepareStatement(query);
        ps_e.setInt(1, Integer.parseInt(inputID.getText()));
        ResultSet res_e = ps_e.executeQuery();
        
        if (res_e.next()) {
            employee = new Empleado(
                res_e.getString("email"),
                res_e.getString("telefono"),
                res_e.getString("direccion"), 
                res_e.getString("colonia"), 
                Integer.parseInt(res_e.getString("zp")), 
                res_e.getString("nombre"), 
                res_e.getString("apellidoP"), 
                res_e.getString("apellidoM"), 
                res.getString("user"), 
                res.getString("password"), 
                res_e.getInt("empleadoId"), 
                res_e.getString("puesto"));
         
            JOptionPane.showMessageDialog(this, employee.showData());
                 }
            }
        } catch(SQLException err) {
            System.out.println("Hubo un error para consultar los datos: " + err);
        }
       }
    }//GEN-LAST:event_showDataActionPerformed

    private void addDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDataActionPerformed
        // TODO add your handling code here:
        clearInputs();
        registerButton.setEnabled(true);
        inputID.setEditable(false);

    }//GEN-LAST:event_addDataActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        // TODO add your handling code here:
        addData();
        query();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void deletDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletDataActionPerformed
        // TODO add your handling code here:
        registerButton.setEnabled(false);
        deleteData();
        query();
    }//GEN-LAST:event_deletDataActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        registerButton.setEnabled(false);
        int fila = Tabla.getSelectedRow();
        
        if (fila == -1){
            JOptionPane.showMessageDialog(this, "No se encontro la fila.");
        } else {
            
            int empleadoId = Integer.parseInt(String.valueOf(Tabla.getValueAt(fila, 0)));
//            Tabla.setCellSelectionEnabled(true);
//            String nom = (String) Tabla.getValueAt(fila, 1);
//            String ape = (String) Tabla.getValueAt(fila, 2);
//            String puestoE = (String) Tabla.getValueAt(fila, 3);
            
            String sql = "select * from empleado where empleadoId=?";
            try {
            PreparedStatement ps = conexion.prepareStatement(sql);
            ps.setInt(1, empleadoId);
            ResultSet rs = ps.executeQuery();
            
            if (rs.next()){
                 inputID.setText(""+empleadoId);
                 inputName.setText(rs.getString("nombre"));
                 inputLNP.setText(rs.getString("apellidoP"));
                 inputLNM.setText(rs.getString("apellidoM"));
                 inputAddress.setText(rs.getString("direccion"));
                 inputCol.setText(rs.getString("colonia"));
                 inputZC.setText(rs.getString("zp"));
                 inputEmail.setText(rs.getString("email"));
                 inputPuesto.setText(rs.getString("puesto"));
                 inputPhone.setText(rs.getString("telefono"));
            }
           
        }catch (SQLException e){
            System.out.println("Hubo un error para consultar los datos: " + e);
        }
           
            
        }
    }//GEN-LAST:event_TablaMouseClicked

    private void TablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaPropertyChange
        // TODO add your handling code here:
    
    }//GEN-LAST:event_TablaPropertyChange

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y- yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement();
        em.setVisible(true);
        em.pack();
        this.dispose();
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
        // TODO add your handling code here:
        PatientManagement pm = new PatientManagement();
        pm.setVisible(true);
        pm.pack();
        this.dispose();
    }//GEN-LAST:event_btnPetsActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        // TODO add your handling code here:
        ClientManagement cm = new ClientManagement();
        cm.setVisible(true);
        cm.pack();
        this.dispose();
    }//GEN-LAST:event_btnClientActionPerformed

    private void btnDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountsActionPerformed
        // TODO add your handling code here:
        DiscountManagement dm = new DiscountManagement();
        dm.setVisible(true);
        dm.pack();
        this.dispose();
    }//GEN-LAST:event_btnDiscountsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        ServicesManagement sm = new ServicesManagement();
        sm.setVisible(true);
        sm.pack();
        this.dispose();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        QueryBills qb = new QueryBills();
        qb.setVisible(true);
        qb.pack();
        this.dispose();
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        Menu mm = new Menu();
        mm.setVisible(true);
        mm.pack();
        this.dispose();
    }//GEN-LAST:event_btnMainActionPerformed

    private void addData(){
        Map<String, String> lista = new LinkedHashMap<>();
        String errorMessage = "";
        
        lista.put("Nombre", inputName.getText());
        lista.put("Apellido Paterno", inputLNP.getText());
        lista.put("Apellido Materno", inputLNM.getText());
        lista.put("Direccion", inputAddress.getText());
        lista.put("Colonia", inputCol.getText());
        lista.put("Codigo Postal", inputZC.getText());
        lista.put("Correo", inputEmail.getText());
        lista.put("Puesto", inputPuesto.getText());
        lista.put("Telefono", inputPhone.getText());
        
        for (Map.Entry<String, String> entry : lista.entrySet()) {
            if (entry.getValue().isEmpty()) {
                errorMessage += entry.getKey() + ", ";
            }
        }
        
                 int lastIndex = errorMessage.lastIndexOf(",");
        if (lastIndex >= 0) {
            errorMessage = errorMessage.substring(0, lastIndex) + "." + errorMessage.substring(lastIndex + 1);
        }
        if (!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(this, "Los siguientes campos deben ser completados: " + errorMessage);
        } else {
             try {
                ZipCode = Integer.parseInt(inputZC.getText());
                try {
                    Phone = new BigInteger(inputPhone.getText());
                    if(inputEmail.getText().contains("@") && inputEmail.getText().contains(".") && !inputEmail.getText().contains(" ")){
            
                         db.insertEmployeeData(lista);
                         
                     } else {
                             JOptionPane.showMessageDialog(this, "El correo ingresado no es valido\nIntentalo de nuevo.");
                        }
 
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "El numero de telefono debe ser numerico.");
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El codigo postal debe ser numerico.");
            }
//                db.insertEmployeeData(lista);
        }
        
        clearTable();
        clearInputs();
    }
    
    private void query(){
        String sql = "select * from empleado";
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            Object[] empleado = new Object[4];
            modelo = (DefaultTableModel) Tabla.getModel();
            
            while(rs.next()){
                empleado [0] = rs.getInt("empleadoId");
                empleado [1] = rs.getString("nombre");
                empleado [2] = rs.getString("apellidoP");
                empleado [3] = rs.getString("puesto");
                
                modelo.addRow(empleado);
                
            }
            Tabla.setModel(modelo);
        }catch (SQLException e){
            System.out.println("Hubo un error para consultar los datos: " + e);
        }
    }
    
    private void modify(){
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un empleado.");
        } else {
        Map<String, String> lista = new LinkedHashMap<>();
        String errorMessage = "";
        
        lista.put("Nombre", inputName.getText());
        lista.put("Apellido Paterno", inputLNP.getText());
        lista.put("Apellido Materno", inputLNM.getText());
        lista.put("Direccion", inputAddress.getText());
        lista.put("Colonia", inputCol.getText());
        lista.put("Codigo Postal", inputZC.getText());
        lista.put("Correo", inputEmail.getText());
        lista.put("Puesto", inputPuesto.getText());
        lista.put("Telefono", inputPhone.getText());
        
        for (Map.Entry<String, String> entry : lista.entrySet()) {
            if (entry.getValue().isEmpty()) {
                errorMessage += entry.getKey() + ", ";
            }
        }
        
                 int lastIndex = errorMessage.lastIndexOf(",");
        if (lastIndex >= 0) {
            errorMessage = errorMessage.substring(0, lastIndex) + "." + errorMessage.substring(lastIndex + 1);
        }
        if (!errorMessage.isEmpty()){
            JOptionPane.showMessageDialog(this, "Los siguientes campos no pueden estar vacios: " + errorMessage);
        } else {
             try {
                ZipCode = Integer.parseInt(inputZC.getText());
                try {
                    Phone = new BigInteger(inputPhone.getText());
                    if(inputEmail.getText().contains("@") && inputEmail.getText().contains(".") && !inputEmail.getText().contains(" ")){
            
//                         db.insertEmployeeData(lista);
                           db.editEmployeeData(lista, Integer.parseInt(inputID.getText()));
                     } else {
                             JOptionPane.showMessageDialog(this, "El correo ingresado no es valido\nIntentalo de nuevo.");
                        }
 
                }catch (NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "El numero de telefono debe ser numerico.");
                }
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "El codigo postal debe ser numerico.");
            }
//                db.insertEmployeeData(lista);
        }
       }
        
        clearTable();
        clearInputs();
    }
    
    private void deleteData(){
         int fila = Tabla.getSelectedRow();
        
        if (fila == -1 || inputID.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha seleccionado un empleado.");
        } else {
       String sql = "delete from empleado_user where empleadoId=?";
       int r = 0;
       try{
                PreparedStatement ps = conexion.prepareStatement(sql);
                ps.setInt(1, Integer.parseInt(inputID.getText()));
                r = ps.executeUpdate();
                
                 String script = "delete from empleado where empleadoId=?";
                 int r2 = 0;
                 try{
                    PreparedStatement ps2 = conexion.prepareStatement(script);
                    ps2.setInt(1, Integer.parseInt(inputID.getText()));
                    r2 = ps2.executeUpdate();
                    
                    if(r != 0 ){
                        JOptionPane.showMessageDialog(this, "¡Se eliminaron los datos correctamente!");
                    }
                    } catch (SQLException err) {
                
                     System.out.println("Hubo un error al elliminar datos en la tabla empleado_user: " + err);
                
                    }
            } catch (SQLException err) {
                
                System.out.println("Hubo un error al elliminar datos en la tabla empleado: " + err);
                
            }
        }
      
        clearTable();
        clearInputs();
    }
    
    private void clearTable(){
        while (Tabla.getRowCount() > 0){
        modelo.removeRow(0);
        }
    }
    
    
    public void clearInputs(){
        inputID.setText("");
        inputName.setText("");
        inputLNP.setText("");
        inputLNM.setText("");
        inputAddress.setText("");
        inputCol.setText("");
        inputZC.setText("");
        inputEmail.setText("");
        inputPuesto.setText("");
        inputPhone.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagement().setVisible(true);
            }
        });
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton addData;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnDiscounts;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnPets;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton deletData;
    private javax.swing.JButton editData;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputCol;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputID;
    private javax.swing.JTextField inputLNM;
    private javax.swing.JTextField inputLNP;
    private javax.swing.JTextField inputName;
    private javax.swing.JTextField inputPhone;
    private javax.swing.JTextField inputPuesto;
    private javax.swing.JTextField inputZC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton showData;
    // End of variables declaration//GEN-END:variables
}
