/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import java.sql.*;
import misclases.Empleado;
import system.*;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {
    DataBase db = new DataBase();
    Connection conexion = db.getConnected();
    /**
     * Creates new form Login
     */
    int yMouse, xMouse;

    /**
     * Creates new form Login
     */
  
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Veterinaria");
    }
    
    public Image getIconImage(){
        Image res = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\pies.png");
        return res;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        perro = new javax.swing.JLabel();
        gato = new javax.swing.JLabel();
        circulo = new javax.swing.JLabel();
        patitas = new javax.swing.JLabel();
        textUser = new javax.swing.JLabel();
        textPassword = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        inputPassword = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        contenedor = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();
        header = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        perro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\puppy.png")); // NOI18N
        getContentPane().add(perro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        gato.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\gato.png")); // NOI18N
        getContentPane().add(gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 180, 150));

        circulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\marco.png")); // NOI18N
        getContentPane().add(circulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 260, 270));

        patitas.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\pies.png")); // NOI18N
        getContentPane().add(patitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        textUser.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        textUser.setForeground(new java.awt.Color(255, 255, 255));
        textUser.setText("Usuario");
        getContentPane().add(textUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, -1, -1));

        textPassword.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        textPassword.setForeground(new java.awt.Color(255, 255, 255));
        textPassword.setText("Contraseña");
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 660, -1, -1));

        inputUsername.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        getContentPane().add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 280, 50));

        inputPassword.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 280, 50));

        jButton2.setBackground(new java.awt.Color(51, 102, 0));
        jButton2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 780, 110, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 204));
        jLabel1.setText("Iniciar Sesión");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        contenedor.setBackground(new java.awt.Color(255, 0, 153));
        contenedor.setForeground(new java.awt.Color(204, 51, 255));
        contenedor.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\capa.png")); // NOI18N
        contenedor.setIconTextGap(7);
        getContentPane().add(contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 430, 620, 410));

        jLabel2.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel2.setText("Veterinaria");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 300, 40));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Salir");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\Proyectos\\Veterinaria\\Imagenes\\uwu.jpg")); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 850));

        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 560, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String inputUser = inputUsername.getText();
        String inputPass = String.valueOf(inputPassword.getPassword());
        String admin_user = "admin";
        String admin_pass = "erth.data";
        if (inputUser.length() == 0){
            JOptionPane.showMessageDialog(this, "Debes llenar el campo de usuario.");
        } else if (inputPass.length() == 0){
            JOptionPane.showMessageDialog(this, "Debes llenar el campo de la contraseña.");
        } else if (inputUser.equals(admin_user) && inputPass.equals(admin_pass)){
            JOptionPane.showMessageDialog(this, "Iniciaste sesion correctamente :D");
            Empleado employee = new Empleado("erthdataservice@hotmail.com","333356987","Arboledas #486", "Zapopan.", 45180, "admin","","","admin","erth.data", 0, "owner");
            Menu principal = new Menu(employee, conexion);
                this.setVisible(false);
                this.dispose();
                principal.setVisible(true);
                principal.pack();
        } else {
            Empleado employee = db.getLogin(inputUser);
            if (employee == null || !employee.getPassword().equals(inputPass)){
                //System.out.println("Aqui");
                JOptionPane.showMessageDialog(this, "Las credenciales no son validas :(");
            } else {
                JOptionPane.showMessageDialog(this, "Iniciaste sesion correctamente :D");
                Menu principal = new Menu(employee, conexion);
                this.setVisible(false);
                this.dispose();
                principal.setVisible(true);
                principal.pack();
            }
            
        }

       //javax.swing.JOptionPane.showMessageDialog(this, "Usted ha ingresado: \nUsuario: "  + "\nPassword: " + String.valueOf(inputPassword.getPassword()));
        inputUsername.setText("");
        inputPassword.setText("");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//
//        /* Create and display the form */
//        
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//                
//            }
//        });
//        
//        
//        
//     
//        
//        
//     
//    }
    
    class RoundBorder extends AbstractBorder {
        
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x, y, width-1, height-1, 15, 15);
        }
        
        public Insets getBorderInsets(Component c) {
            return new Insets(10, 10, 10, 10);
        }
        
        public Insets getBorderInsets(Component c, Insets insets) {
            insets.left = insets.top = insets.right = insets.bottom = 10;
            return insets;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel circulo;
    private javax.swing.JLabel contenedor;
    private javax.swing.JLabel gato;
    private javax.swing.JPanel header;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel patitas;
    private javax.swing.JLabel perro;
    private javax.swing.JLabel textPassword;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
