/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.awt.Color;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import misclases.*;
import system.DataBase;

/**
 *
 * @author Asus
 */
public class Menu extends javax.swing.JFrame {
    int yMouse, xMouse;
    final private ArrayList<Servicio[]> listaServicios = new ArrayList<>();
    final private ArrayList<Mascota> listaMascota = new ArrayList<>();
    private Empleado me = null;
    Descuento descuentouwu = null;
    final private ArrayList<Cliente> ayuda = new ArrayList<>();
    private DefaultTableModel modelo;
    Cliente objetoBuscado = null;
    private boolean Continue;
    
//    Connection conexion = null;
     DataBase db = new DataBase();
     Connection conexion = db.getConnected();
    /**
     * Creates new form Menu
     * @param user
     * @param db
     */
    //Empleado user, Connection db
    public Menu() {
//        me = user;
//        conexion = db;
        Continue = false;
        me = new Empleado("erthdataservice@hotmail.com","333356987","Arboledas #486", "Zapopan.", 45180, "admin","","","admin","erth.data", 32, "owner");
        initComponents();
        setLocationRelativeTo(null);
        fillBox();
        setDatos();

    }
    public void setContinue(boolean flag){
        this.Continue = flag;
    }
    
    public void addServices(Servicio[] services){
        listaServicios.add(services);
    }
    
    public boolean petExists(String n){
        for (Mascota mascota : listaMascota) {
            if (mascota.getNombre().equals(n))  return true;
        }
        return false;
        
    }
    
    public void addMascota(Mascota pet){
        listaMascota.add(pet);
    }
    
    public void updateTable(){
            Object[] info = new Object[4];
            modelo = (DefaultTableModel) Tabla.getModel();
            double suma = 0;
            for (Mascota owo : listaMascota){
               info [0] = owo.getPetId();
           } 
           for (Mascota owo : listaMascota){
               info [1] = owo.getNombre();
           }
           
            

                for (Servicio[] arrayS : listaServicios){
                    StringBuilder nombresServicios = new StringBuilder();
                    for (Servicio s : arrayS){
                        if (nombresServicios.length() > 0) {
                            nombresServicios.append(", ");
                            }
                         nombresServicios.append(s.getTipo());
                        }
                     info[2] = nombresServicios.toString();
                   }
                
                
                for (Servicio[] arrayS : listaServicios){
                    double total = 0;
                    for (Servicio s : arrayS){
                        total += s.getPrecio();
                        }
                     suma+=total;
                     info[3] = "$ " + total;
                   }
                   
            double[] valores = calcularDescuento(suma);   
            modelo.addRow(info);
            txtTotal.setText("$"+ valores[0] + "");
            txtDescuento.setText(listaMascota.size() > 1 ?  String.valueOf(valores[1]).replace(".0", "") + "%"  : "Ninguno");
            Tabla.setModel(modelo);
    }
    
    private void fillBox(){
         ClientsBox.addItem("Ninguno");
        String sql = "select * from cliente";
        try {
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String n = rs.getString("nombre");
                String p = rs.getString("apellidoP");
                String m = rs.getString("apellidoM");
                ayuda.add(new Cliente(rs.getString("email"),
                rs.getString("tel_cel"),
                rs.getString("direccion"), 
                rs.getString("colonia"), 
                Integer.parseInt(rs.getString("zp")), 
                rs.getString("nombre"), 
                rs.getString("apellidoP"), 
                rs.getString("apellidoM"), 
                rs.getInt("clienteId"), 
                rs.getString("tel_casa")));
                ClientsBox.addItem(n + " " +p + " " + m);
            }
        }catch (SQLException e){
            System.out.println("Hubo un error para consultar los datos: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        addpatient = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clicHere = new javax.swing.JLabel();
        ClientsBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        generateInvoice = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmpleado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JButton();
        btnPets = new javax.swing.JButton();
        btnClient = new javax.swing.JButton();
        btnDiscounts = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnLogs = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 0, 204));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Salir");
        btnExit.setFocusPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setText("Generacion de facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 37));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acerca de la consulta"));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MascotaId", "Nombre Mascota", "Servicio(s)", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        Tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        addpatient.setText("Agregar paciente");
        addpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addpatient))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addpatient)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 724, 320));

        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 50, -1));

        jLabel5.setText("¿No encuentras al cliente?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 170, 20));

        clicHere.setForeground(new java.awt.Color(0, 66, 255));
        clicHere.setText("Agregalo aqui.");
        clicHere.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clicHereMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                clicHereMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                clicHereMouseExited(evt);
            }
        });
        getContentPane().add(clicHere, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 100, 20));

        ClientsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientsBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ClientsBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 199, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles de la factura"));

        generateInvoice.setText("Generar Factura");
        generateInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateInvoiceActionPerformed(evt);
            }
        });

        jLabel3.setText("Total: ");

        txtTotal.setText("$0.00");

        jLabel4.setText("Descuento aplicado:");

        txtDescuento.setText("Ninguno");

        jLabel6.setText("Fecha:");

        jLabel7.setText("Empleado que lo genero: ");

        txtEmpleado.setText("Desconocido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                        .addComponent(generateInvoice))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescuento)
                            .addComponent(txtEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescuento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generateInvoice)
                        .addComponent(jLabel6))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 720, 140));

        jPanel5.setBackground(new java.awt.Color(102, 102, 255));

        btnEmployee.setText("Empleados");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        btnPets.setText("Mascotas");
        btnPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetsActionPerformed(evt);
            }
        });

        btnClient.setText("Clientes");
        btnClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientActionPerformed(evt);
            }
        });

        btnDiscounts.setText("Descuentos");
        btnDiscounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountsActionPerformed(evt);
            }
        });

        btnServices.setText("Servicios");
        btnServices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServicesActionPerformed(evt);
            }
        });

        btnLogs.setText("Registros");
        btnLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogsActionPerformed(evt);
            }
        });

        btnMain.setText("Menu Prinpal");
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPets, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDiscounts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnClient, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPets, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnDiscounts, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnServices, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y- yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_TablaMouseClicked

    private void TablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TablaPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_TablaPropertyChange

    private void addpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientActionPerformed
        // TODO add your handling code here:
        if (ClientsBox.getSelectedItem().toString().equals("Ninguno")){
            JOptionPane.showMessageDialog(this, "Debes seleccionar un clientes antes de agregar un paciente.");
        } else {
              ClientsBox.setEnabled(false);
              for (Cliente obj : ayuda) {
              String fullName = obj.getName() + " " + obj.getLastNameP()+ " " + obj.getLastNameM();    
        
              if (fullName.equals(ClientsBox.getSelectedItem().toString().toUpperCase())) {
                objetoBuscado = obj;
                break;
                }
              }
              int OwnerId = objetoBuscado.getClienteId();
              AddPatient Lwindow = new  AddPatient(this, OwnerId);
              Lwindow.setVisible(true);
        }
   
        
    }//GEN-LAST:event_addpatientActionPerformed

    private void clicHereMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicHereMouseClicked
        // TODO add your handling code here:
        ClientManagement cm = new ClientManagement();
        cm.setVisible(true);
        cm.pack();
        this.dispose();
    }//GEN-LAST:event_clicHereMouseClicked

    private void clicHereMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicHereMouseEntered
        // TODO add your handling code here:
        clicHere.setForeground(new Color(   0, 143, 255  ));
        clicHere.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_clicHereMouseEntered

    private void clicHereMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicHereMouseExited
        // TODO add your handling code here:
        clicHere.setForeground(new Color(0, 66, 255));
    }//GEN-LAST:event_clicHereMouseExited

    private void ClientsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientsBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientsBoxActionPerformed

    private void generateInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateInvoiceActionPerformed
        // TODO add your handling code here:
        //createBills(double amount, Descuento d, Cliente c, ArrayList<Mascota> listaMascota,  ArrayList<Servicio[]> listaServicios)
       if (!this.Continue){
           JOptionPane.showMessageDialog(this, "Necesitas agregar pacientes con el servicio \nque necesitan para generar una factura");
       } else {
        if (txtDescuento.getText().equals("15%")){
            descuentouwu = new Descuento();
            descuentouwu.setDiscountId(1);
        } else if (txtDescuento.getText().equals("25%")) {
            descuentouwu = new Descuento();
            descuentouwu.setDiscountId(2);
        } else descuentouwu = null;
        setContinue(false);
        db.createBills(Float.parseFloat(txtTotal.getText().replace("$", "")), descuentouwu, objetoBuscado, listaMascota, listaServicios, me );
        listaMascota.clear();
        listaServicios.clear();
        clearTable();
        ClientsBox.setEnabled(true);
        
       }
        
    }//GEN-LAST:event_generateInvoiceActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement();
        em.setVisible(true);
        em.pack();
        this.dispose();
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
        // TODO add your handling code here:
        PatientManagement pm = new PatientManagement();
        pm.setVisible(true);
        pm.pack();
        this.dispose();
    }//GEN-LAST:event_btnPetsActionPerformed

    private void btnClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientActionPerformed
        // TODO add your handling code here:
        ClientManagement cm = new ClientManagement();
        cm.setVisible(true);
        cm.pack();
        this.dispose();
    }//GEN-LAST:event_btnClientActionPerformed

    private void btnDiscountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountsActionPerformed
        // TODO add your handling code here:
        DiscountManagement dm = new DiscountManagement();
        dm.setVisible(true);
        dm.pack();
        this.dispose();
    }//GEN-LAST:event_btnDiscountsActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
        // TODO add your handling code here:
        ServicesManagement sm = new ServicesManagement();
        sm.setVisible(true);
        sm.pack();
        this.dispose();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogsActionPerformed
        // TODO add your handling code here:
        QueryBills qb = new QueryBills();
        qb.setVisible(true);
        qb.pack();
        this.dispose();
    }//GEN-LAST:event_btnLogsActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        Menu mm = new Menu();
        mm.setVisible(true);
        mm.pack();
        this.dispose();
    }//GEN-LAST:event_btnMainActionPerformed

    private void setDatos(){
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy hh:mm");
        Date fechaActual = new Date();
        String fechaComoCadena = formatoFecha.format(fechaActual);
        txtFecha.setText(fechaComoCadena);
        txtEmpleado.setText(me.getName() + " " + me.getLastNameP() + " " + me.getLastNameM());
    }
    
    private void clearTable(){
        while (Tabla.getRowCount() > 0){
        modelo.removeRow(0);
        }
    }
    
    public double[] calcularDescuento(double total) {
    int numMascotas = listaMascota.size();
    double descuento = 0;
    int porcentajeDescuento = 0;

    if (numMascotas == 2) {
        porcentajeDescuento = 15;  // 15% de descuento
        descuento = total * (porcentajeDescuento / 100.0);
    } else if (numMascotas >= 3) {
        porcentajeDescuento = 25;  // 25% de descuento
        descuento = total * (porcentajeDescuento / 100.0);
    }

    double[] resultado = {total - descuento, porcentajeDescuento};
    return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
        
      
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClientsBox;
    private javax.swing.JTable Tabla;
    private javax.swing.JToggleButton addpatient;
    private javax.swing.JButton btnClient;
    private javax.swing.JButton btnDiscounts;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogs;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnPets;
    private javax.swing.JButton btnServices;
    private javax.swing.JLabel clicHere;
    private javax.swing.JToggleButton generateInvoice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtDescuento;
    private javax.swing.JLabel txtEmpleado;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
